/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esportsapp;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author j9neave
 */
public class Member extends javax.swing.JPanel {

	static List<Member> list = new ArrayList<Member>();
	
	String name;
	Team team;
	int score;
	Map<Event, Integer> eventScores;
	
	/**
	 * Creates new form Member
	 */
	private Member(String name, Team team) {
		this.eventScores = new HashMap<>();
		this.name = name;
		this.team = team;
		this.score = 0;
		
		
		initComponents();
	}
	
	public static Member add(String name, Team team) {
		Member mem = new Member(name, team);
		
		mem.team.memberScores.put(mem, mem.score);
		Member.list.add(mem);
		
		return mem;
	}
	
	public void setScoreForEvent(Event evt, int scr) {
		this.eventScores.put(evt, scr);
		int tot = 0;
		for (int scr2 : this.eventScores.values()) tot += scr2;
		this.score = tot;
		this.team.memberScores.put(this, tot);	
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
