/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esportsapp;

/**
 *
 * @author User
 */
public class Team extends javax.swing.JPanel {

	/**
	 * Creates new form Team
	 */
	public Team() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        EventsLabel = new javax.swing.JLabel();
        TeamRemoveMember = new javax.swing.JButton();
        MembersLabel = new javax.swing.JLabel();
        TeamAddMember = new javax.swing.JButton();
        TeamRenameButton = new javax.swing.JButton();
        TeamEventsScrollPane = new javax.swing.JScrollPane();
        TeamEventsList = new javax.swing.JList<>();
        TeamMembersScrollPane = new javax.swing.JScrollPane();
        TeamMembersList = new javax.swing.JList<>();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        EventsLabel.setText("Events:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        add(EventsLabel, gridBagConstraints);

        TeamRemoveMember.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(TeamRemoveMember, gridBagConstraints);

        MembersLabel.setText("Members:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(MembersLabel, gridBagConstraints);

        TeamAddMember.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        add(TeamAddMember, gridBagConstraints);

        TeamRenameButton.setText("Rename");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TeamRenameButton, gridBagConstraints);

        TeamEventsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Event1", "Event2", "Event3", "Event4", "Event5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TeamEventsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TeamEventsScrollPane.setViewportView(TeamEventsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TeamEventsScrollPane, gridBagConstraints);

        TeamMembersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Member1", "Member2", "Member3", "Member4", "Member5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TeamMembersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TeamMembersScrollPane.setViewportView(TeamMembersList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(TeamMembersScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EventsLabel;
    private javax.swing.JLabel MembersLabel;
    private javax.swing.JButton TeamAddMember;
    private javax.swing.JList<String> TeamEventsList;
    private javax.swing.JScrollPane TeamEventsScrollPane;
    private javax.swing.JList<String> TeamMembersList;
    private javax.swing.JScrollPane TeamMembersScrollPane;
    private javax.swing.JButton TeamRemoveMember;
    private javax.swing.JButton TeamRenameButton;
    // End of variables declaration//GEN-END:variables
}
