/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esportsapp;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author User
 */
public class Team extends javax.swing.JPanel {

	public static List<Team> list = new ArrayList<Team>();
	
	String name;
	int score = 0;
	Map<Member, Integer> memberScores;
	
	/**
	 * Creates new form Team
	 */
	private Team(String name) {
		this.memberScores = new HashMap<>();
		this.name = name;
		this.score = 0;
		
		
		initComponents();
	}
	
	public static Team add(String name) {
		name = name.trim();
		Team tm = new Team(name);
		
		Team.list.add(tm);
		
		return tm;
	}
	
	public void updateScore() {
		int tot = 0;
		tot = Event.list.stream()
				.map(evt -> evt.teamScores.get(this))
				.filter(scr -> (scr != null))
				.reduce(tot, Integer::sum);
		this.score = tot;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setMinimumSize(new java.awt.Dimension(0, 40));
        setOpaque(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.columnWeights = new double[] {0.0};
        layout.rowWeights = new double[] {0.0};
        setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
